# Generated by Django 4.2.13 on 2026-02-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list, verbose_name='Размеры'),
        ),
    ]
