# Generated by Django 4.2.13 on 2026-03-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hoodie', 'Худи'), ('longsleeves', 'Лонгсливы'), ('shirts', 'Футболки')], max_length=50, verbose_name='Категория'),
        ),
    ]
